staging_certbot_options: "--email some@email.com --server https://127.0.0.1:14000/dir --no-verify-ssl"
production_certbot_options: "--email prod@email.com --server https://acme-v02.api.letsencrypt.org/directory"
controller_domain: test.me.uk
controller_ip: 1.2.3.4  # the controller IP
controller_hostname: test.me.uk
doh_private_port: 8085
kibana_private_port: 5601
ssl_ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA"
edge_names_to_ips:
  controller: 1.2.3.4 # the controller IP
  edge1.domain.com: 2.3.4.5 # edge names to IPs
  edge2.domain.com: 3.4.5.6
edge_names_to_dnets:
  edge1.domain.com: "dnet_a"  # edge names to dnet names
  edge2.domain.com: "dnet_b"
dnets_to_edges:
  controller:
  - controller
  dnet_a:
  - edge1.domain.com
  dnet_b:
  - edge2.domain.com
edge_username: edge_username  # SSH username of an edge
banjax_next:
  gin_log_file: /var/log/banjax-next/gin.log
  metrics_log_file: /var/log/banjax-next/metrics.log
  hmac_secret: 'the hmac secret'
  expiring_decision_ttl_seconds: 60
  too_many_failed_challenges_interval_seconds: 30
  too_many_failed_challenges_threshold: 10
  password_cookie_ttl_seconds: 3600
  sha_inv_cookie_ttl_seconds: 3600
  password_protected_paths:
    "adomain.com":
      - wp-admin
  password_hashes:
    "adomain.com": "the password hash for the path specified above"
  server_log_file: "/var/log/banjax-next/banjax-next-format.log"
  banning_log_file: "/var/log/banjax-next/banjax-logstash-format.log"
  iptables_ban_seconds: 60
  iptables_unbanner_seconds: 10  # how often we check for and remove old bans
  kafka_brokers:  # for Baskerville communication
    - "IP1:port1"
    - "IP1:port2"
  kafka_security_protocol: 'ssl'
  kafka_ssl_ca: "/etc/banjax-next/caroot.pem"
  kafka_ssl_cert: "/etc/banjax-next/certificate.pem"
  kafka_ssl_key: "/etc/banjax-next/key.pem"
  kafka_ssl_key_password: "kafka ssl key password"
  kafka_report_topic: 'banjax_report_topic'
  kafka_command_topic: 'banjax_command_topic'
  global_decision_lists:
    'challenge':
      - '8.8.8.8'
    'allow':
      - '20.20.20.20'
    'iptables_block':
      - '30.40.50.60'
  regexes_with_rates:
    - rule: 'instant nginx block'
      regex: '.*blockme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'nginx_block'
    - rule: 'instant iptables block'
      regex: '.*iptablesbanme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'iptables_block'
    - rule: 'instant challenge'
      regex: '.*challengeme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'challenge'
    - rule: 'challenge 30 POST per 60 seconds'
      regex: '^POST .*'
      interval: 60
      hits_per_interval: 30
      decision: 'challenge'
    - rule: 'unblocking backdoor'
      regex: '.*allowme.*'
      interval: 1
      hits_per_interval: 0
      decision: 'allow'
