FROM "docker.elastic.co/elasticsearch/elasticsearch:7.12.1"

COPY ./instance.key /usr/share/elasticsearch/config/instance.key
COPY ./instance.crt /usr/share/elasticsearch/config/instance.crt
COPY ./ca.crt /usr/share/elasticsearch/config/ca.crt
