version: '3.4'
volumes:
  var-log-banjax-next:

services:
  banjax-next:
    build:
      context: ./
      dockerfile: Dockerfile
    # this uses the nginx network namespace so it can set iptables rules
    # in the right place. the go app listens on port 8081
    network_mode: "service:nginx"
    cap_add:
      - NET_ADMIN  # we use iptables for banning
    volumes:
      - /var/log/banjax-next/:/var/log/banjax-next/

  nginx:
    build:
      context: ./supporting-containers/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /var/log/banjax-next/:/var/log/banjax-next/
      - /var/log/nginx/:/var/log/nginx/

  test-origin:
    build:
      context: ./supporting-containers/test-origin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
