gin_log_file: /var/log/banjax/gin.log
metrics_log_file: /var/log/banjax/metrics.log
hmac_secret: 'the hmac secret'
expiring_decision_ttl_seconds: 60
too_many_failed_challenges_interval_seconds: 30
too_many_failed_challenges_threshold: 10
password_cookie_ttl_seconds: 3600
sha_inv_cookie_ttl_seconds: 3600
server_log_file: "/var/log/banjax/banjax-format.log"
banning_log_file: "/var/log/banjax/banjax-logstash-format.log"
iptables_ban_seconds: 60
iptables_unbanner_seconds: 10  # how often we check for and remove old bans
kafka_brokers:  # for Baskerville communication
  - "IP1:port1"
  - "IP1:port2"
kafka_security_protocol: 'ssl'
kafka_ssl_ca: "/etc/banjax/caroot.pem"
kafka_ssl_cert: "/etc/banjax/certificate.pem"
kafka_ssl_key: "/etc/banjax/key.pem"
kafka_ssl_key_password: "kafka ssl key password"
kafka_report_topic: 'banjax_report_topic'
kafka_command_topic: 'banjax_command_topic'
global_decision_lists:
  'challenge':
    - '8.8.8.8'
  'allow':
    - '20.20.20.20'
  'iptables_block':
    - '30.40.50.60'
regexes_with_rates:
  - rule: 'instant nginx block'
    regex: '.*blockme.*'
    interval: 1
    hits_per_interval: 0
    decision: 'nginx_block'
  - rule: 'instant iptables block'
    regex: '.*iptablesbanme.*'
    interval: 1
    hits_per_interval: 0
    decision: 'iptables_block'
  - rule: 'instant challenge'
    regex: '.*challengeme.*'
    interval: 1
    hits_per_interval: 0
    decision: 'challenge'
  - rule: 'challenge 30 POST per 60 seconds'
    regex: '^POST .*'
    interval: 60
    hits_per_interval: 30
    decision: 'challenge'
  - rule: 'unblocking backdoor'
    regex: '.*allowme.*'
    interval: 1
    hits_per_interval: 0
    decision: 'allow'
