system_root_zone: example.com
login_user: deflect
dnets:
  - dnet_a
  - controller  # XXX fix this
controller:
  hostname: controller.example.com
  ip: 1.2.3.4
  docker_ip: 127.0.0.1  # connect to local docker without SSH
  dnet: controller  # XXX fix this
  user: deflect
edges:
  - hostname: edge-1.example.comp
    ip: 2.3.4.5
    dnet: dnet_a
    user: deflect
staging_certbot_options: "--email some@email.com --server https://127.0.0.1:14000/dir --no-verify-ssl"
production_certbot_options: "--email prod@email.com --server https://acme-v02.api.letsencrypt.org/directory"
doh_private_port: 8085
kibana_private_port: 5601
ssl_ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA"
