from config_generation.bind import generate_bind_config
from config_generation.nginx import generate_nginx_config
from config_generation.banjax import generate_banjax_config
from config_generation.edgemanage import generate_edgemanage_config
from config_generation.legacy_filebeat import generate_legacy_filebeat_config
